// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $growth_plan from "./routes/growth-plan.tsx";
import * as $index from "./routes/index.tsx";
import * as $philosophy from "./routes/philosophy.tsx";
import * as $resume from "./routes/resume.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/growth-plan.tsx": $growth_plan,
    "./routes/index.tsx": $index,
    "./routes/philosophy.tsx": $philosophy,
    "./routes/resume.tsx": $resume,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
